[workspace]
members = [
    "edb/edgeql-parser",
    "edb/edgeql-parser/edgeql-parser-derive",
    "edb/edgeql-parser/edgeql-parser-python",
    "edb/graphql-rewrite",
    "edb/server/conn_pool",
]
resolver = "2"

[profile.release]
debug = true
lto = true

[workspace.lints]